### ISSUE TITLE
Install From Web Search

### ISSUE THREAD

**Issue by Avalonmist** [joomla-extensions/install-from-web-client#42] opened 2016-02-29 20:30 UTC
**Steps to reproduce the issue**
In the admin side of Joomla, go to Extensions >> Install
On the Install from Web tab, click into the search field and type 'VirtueMart' (without quotes)
Click the magnifying glass search button
Look for "VirtueMart" within the search results.

**Expected result**
The Name of the extension should be weighted first and therefore the extension "VirtueMart" should have been first before any other extensions with "VirtueMart" in the description. Not sure why "Breezing Forms" keeps popping up first. Sort dropdown box should be defaulted to "Sort be Relevance"

**Actual result**
The "VirtueMart" Extension is not listed, "Breezing Forms" is the first one listed which is not even close to "VirtueMart".

I even tried to go into the e-Commerce category and search from there but it jumped to the "Home" category and guess what? ... "Breezing Forms" is at the top.

**System information (as much as possible)**
Joomla 3.4.8

**Comment by dig814** [comment] 2016-03-11 14:11
I can also confirm this behavior.

**Comment by nicksavov** [comment] 2016-03-11 18:04
+1

**Comment by dig814** [comment] 2016-04-28 17:58
This is still an issue. I noticed a new version of install from web.1.10. Installed but search is still not reliable, making it impossible to find extensions easily. Still same issue as listed above/

**Comment by beat** [comment] 2016-05-13 10:18
I agree that this needs to be addressed, but to the best of my knowledge, it is an issue with the JED API.

Does the JED API now provide such a sorting order=byrelevancy ?

**Comment by kalemanzi** [comment] 2016-08-17 15:30
_I got pointed here from the joomla-cms repo. 
this was what I posted over there, looks more or less the same as what's been pointed out over here._ 

### Steps to reproduce the issue
Try searching for an extension by name in the web installed tab. I searched for "JCE" , "Joomla content editor", "simple image gallery" etc. I've attached some screenshots after search was done:

![screen shot 2016-08-17 at 10 19 18 am](https://cloud.githubusercontent.com/assets/5723384/17729383/4635dada-6464-11e6-8d79-c4d02ea5b8dc.png)
![screen shot 2016-08-17 at 10 18 58 am](https://cloud.githubusercontent.com/assets/5723384/17729384/4662d864-6464-11e6-9b25-0f10d1950b71.png)
![screen shot 2016-08-17 at 10 18 14 am](https://cloud.githubusercontent.com/assets/5723384/17729385/4667ff1a-6464-11e6-983b-fd533cb36d4f.png)

### Expected result
The record which has the closest match should end up on top, eg. JCE Editors' listings as well as JCE related plugins, or something that at least contains the string. 

### Actual result
Heaps of non related extensions, with no mention of the original search string in the results.

### System information (as much as possible)
Vanilla install of Joomla 3.x. As far as I can remember, this is an issue with all the Joomla versions that has the web installer.

### Additional comments
I don't have a solution or PR for this yet, but want to get into the code and see if I can improve the search so that it actually works. 

I don't know how many people use the feature, but it has frustrated me so much in the past, especially when setting up a new site, that I just went and downloaded the extensions direct form the developer sites and did not bother to use the web installer. 

@beat do you know where can I start to look re the JED API? When I do the exact same search direct on the JED, I get the correct results.

**Comment by coolbung** [comment] 2016-08-17 15:44
Please know more about contributing to the JED code here

http://extensions.joomla.org/support/knowledgebase/item/contributing-code-to-the-jed

**Comment by kalemanzi** [comment] 2016-08-17 20:31
Thanks @coolbung - I went ahead and registered over there and will get to the bottom of it.

After looking through the code on install-from-web-client, I now understand that this code simply makes a request to the JED API and the API provides the formatted html in a json format which is then rendered inside the tab where it's updated via an ajax call.

It seems to me that the API and the JED site returns a different search result though, so I suspect they are using different code bases for the API and the JED site. Perhaps the API still uses some code from the previous version of JED. 

This confirms what @beat said about the issue, it's a problem with the API and not install-from-web-client code as such. 

I am going to see if I find something in the JED API code. If I can find the place where the actual db query is constructed, that would be a good place to start.

**Comment by sam-suresh** [comment] 2017-03-30 03:24
Anyone able to work on this? 

Since extensions is important part of CMS, its is bad to have half baked search. 
Sadly, one year past since this reported.

**Comment by dig814** [comment] 2017-03-30 06:09
I do feel this should be a greater priority. In fact it seems to be getting worse. I forever have had the issue with the "Install from Web" tabs' ajax not working. I have to click another tab and back to that tab to see anything. Otherwise its a blank page. Now the "Install from Web"  tab shows by default, "Cannot find any extensions for your version of Joomla. Please try a different search word or another category."
I have the latest version of Joomla installed. I feel this makes Joomla look foolish and would be quite discouraging for new users. This really should work properly or not be included.

**Comment by Bakual** [comment] 2017-03-30 06:27
We can't really add a priority to any of our open issues. It's always a question if some volunteer takes the time (and has the knowledge) to solve the issue.
So if nobody steps up and solves this, it will not get solved.
All the CMS team can do is disable the plugin so it isn't promoted anymore (we did that already once in the past).

**Comment by kalemanzi** [comment] 2017-03-30 08:35
I do apologize on fading on this. I got busy with life and work and completely forgot about this. Currently I have a few deadlines to nail, but will do my level best to look at this next week.

**Comment by sam-suresh** [comment] 2017-03-30 12:02
I can confirm @dig814 that there is a loading issue too. 
In FF, you need to click on that tab again to load it properly. 

If there is no one to fix these issues, we should disable these plugin so people actually can see the problem and come forward to fix it. I see no need to ship broken plugin and service with a great CMS.

**Comment by dig814** [comment] 2017-03-30 15:51
@sam-suresh 
The only "temp" fix is to edit the plugins parameters and set it to display last instead of first in the tab order. This way it at least loads when clicked on but making it work better is another story.

**Comment by beat** [comment] 2017-03-31 09:20
@dig814 

This is not the right tracker to discuss JED server-side search results issues. Please use the JED tracker for it.

Regarding the other issue (first display broken) there is another issue for it: #50 

Thus we should imho close this issue once someone has open an issue at the JED issues tracker ?

**Comment by AlexRed** [comment] 2017-03-31 09:25
Hello beat,
please post the link to the JED issues about this issue

**Comment by AlexRed** [comment] 2017-03-31 10:06
I can't find any issues about "Install From Web"  in the "JED issues tracker":
https://github.com/joomla/jed-issues

**Comment by beat** [comment] 2017-03-31 10:15
@AlexRed iirc there was one in their old? jira? issue tracker. Looks like it didn't get migrated into their new? issue tracker. Please open one, detailed, there, with link to this one, so we can close this one. Thanks a lot!

**Comment by AlexRed** [comment] 2017-03-31 10:32
ok, done: https://github.com/joomla/jed-issues/issues/5

**Comment by beat** [comment] 2017-04-04 07:04
Thanks @AlexRed

**Comment by mbabker** [comment] 2018-09-01 18:05
Search on the server was refactored some time ago to behave more closely with the main JED site search.  Any remaining search related issues should be reported to JED as inherently it's their component that is providing the results.

**Closed by mbabker** 2018-09-01 18:05 UTC
