### ISSUE TITLE
Install the install from web fails to load on page load

### ISSUE THREAD

**Issue by PhilETaylor** [joomla-extensions/install-from-web-client#50] opened 2016-12-11 15:33 UTC
Install from github joomla-cms master at revision 351b778254893d1ebbd734a88e3ad2a33b386aff

Login to admin 

Install the install from web with the button provided 

see that it fails to load the content all the time

<img width="926" alt="screen shot 2016-12-11 at 15 28 57" src="https://cloud.githubusercontent.com/assets/400092/21081078/df91d118-bfb6-11e6-8de9-c157d922dc40.png">

To make it load this correctly you can click another tab and then click the Install from web tab

<img width="902" alt="screen shot 2016-12-11 at 15 32 04" src="https://cloud.githubusercontent.com/assets/400092/21081085/fba99ec6-bfb6-11e6-9d65-9f6e1fdb4418.png">

Cross posted to https://github.com/joomla/joomla-cms/issues/13165

**Comment by PhilETaylor** [comment] 2017-02-02 21:26
still an issue in 3.7.0 beta 1

**Comment by Bakual** [comment] 2017-02-27 20:52
@beat any clue why that happens? Looks like some JavaScript issue to me but I have no clue.

**Comment by Bakual** [comment] 2017-02-27 20:52
Maybe @dgt41 or @fedik have an idea as well.

**Comment by PhilETaylor** [comment] 2017-02-27 20:57
This is still an issue in 3.7b3 
![screen shot 2017-02-27 at 20 57 26](https://cloud.githubusercontent.com/assets/400092/23379588/6a00b228-fd2f-11e6-9be1-bd52cc297493.png)

**Comment by PhilETaylor** [comment] 2017-02-27 21:07
The problem is that 

`apps_installfromon = 0,`

which stops the tab loading.

This is because `apps_installfrom_url = '',` because this method https://github.com/joomla-extensions/install-from-web-client/blob/aa15511fac930dccd1bc1e881fd89b90ff431acb/plugins/installer/webinstaller/webinstaller.php#L173 is not returning anything correct.

**Comment by Fedik** [comment] 2017-02-28 17:49
easy, you just need to click on "Install from Web" tab :neckbeard:  

well, the script do not expect that "Install from Web"  tab can be the first, and it waiting for the "click"
[waiting for the "click"](https://github.com/joomla-extensions/install-from-web-client/blob/aa15511fac930dccd1bc1e881fd89b90ff431acb/plugins/installer/webinstaller/webinstaller.php#L103)

**Comment by PhilETaylor** [comment] 2017-02-28 18:07
> easy, you just need to click on "Install from Web" tab

The tab is already focused and so should initialise on page load - this is the user experience we are aiming for here, rather than have them click away and then click back to the tab.

**Comment by joyhanawa** [comment] 2017-03-21 16:30
The problem is worse than just clicking on the tab.  As of about two weeks ago it says that there are no extensions for your joomla version.  3.6.5

**Comment by AlexRed** [comment] 2017-03-21 16:40
Yes, some day is ok, some day not, some category are ok some not...

**Comment by Webdongle** [comment] 2017-03-21 17:17
I can test when there is a patch

**Comment by beat** [comment] 2017-03-31 09:22
There is probably a simple Javascript fix to be made, which is the only correct fix for this.

I'm currently travelling. If someone can submit a PR in next 3-4 days, then someone can test it and we can then merge it.

Next week, "I'll be back" :-) so if there is hopefully a PR to fix the JS issue, I'll be able to look into it, and merge and release. If not, I'll take the time to fix it in time for 3.7 release, as I'm considering this a high priority issue.

Have a great week-end!

**Comment by N8Solutions** [comment] 2017-04-02 10:18
A clean install of Joomla v3.6.5 is still showing this problem.
Upon installing, it just keeps spinning the "Loading" icon. After clicking on a different tab and coming back to the "Install from Web" I end up getting the error message that says
> Can't connect to the Joomla! server. Please try again later. 

Any idea when this is going to be fixed?

**Comment by AlexRed** [comment] 2017-04-17 11:13
Hello @beat , do you find the time to fix it in time for 3.7 release ?

Regards

**Comment by beat** [comment] 2017-04-23 09:15
A new testing server is in place implementing https://github.com/joomla-extensions/install-from-web-server/pull/36 and should fix the caching issues, thanks @mbabker !

It does not fix the initial load issue which is most probably client-side JS issue probably related with markup-changes in tabs.

Activation + Testing instructions: https://github.com/joomla-extensions/install-from-web-server/pull/36#issuecomment-296429000 + https://github.com/joomla-extensions/install-from-web-server/pull/36

**Comment by Bakual** [comment] 2017-04-23 19:19
> It does not fix the initial load issue which is most probably client-side JS issue probably related with markup-changes in tabs.

If it's related to client side, then it is really an old bug as it is already present in 3.6.5. Probably even older then since both 3.6.4 and 3.6.5 were only security releases.

**Comment by beat** [comment] 2017-04-23 20:27
@Bakual bug is due to a B/C break at some point, it's not important to know exactly when, but to find why and to fix it.

First investigations show that it's in addition loading-timing dependent, as it doesn't happen each time.

**Comment by PhilETaylor** [comment] 2017-04-24 08:22
Please test this PR https://github.com/joomla-extensions/install-from-web-client/pull/52

**Closed** 2017-04-27 23:10 UTC
